/**
 * AMAN CAR — Language / Translations
 * Supports Arabic (ar) and English (en)
 */

const translations = {
  ar: {
    // App
    APP_NAME: 'أمان كار',
    APP_TAGLINE: 'نظام إدارة الورشة',
    STAFF_PORTAL: 'بوابة الموظفين',
    LOADING: 'جاري التحميل...',
    SAVING: 'جاري الحفظ...',
    UPDATING: 'جاري التحديث...',
    PROCESSING: 'جاري المعالجة...',
    SYSTEM_LOADING: 'جاري تحميل النظام...',
    UPDATING_DATA: 'جاري تحديث البيانات...',

    // Auth
    EMAIL_LBL: 'البريد الإلكتروني',
    PASSWORD_LBL: 'كلمة المرور',
    LOGIN_btn: 'تسجيل الدخول',
    REGISTER_btn: 'إنشاء الحساب',
    LOGOUT: 'تسجيل الخروج',
    NO_ACCOUNT: 'ليس لديك حساب؟ أنشئ حسابك الآن',
    HAS_ACCOUNT: 'لديك حساب بالفعل؟ تسجيل الدخول',
    FULL_NAME: 'الاسم الكامل',
    LOGIN_NOTE: 'ملاحظة: النظام متصل بقاعدة بيانات حقيقية. سيتم الدخول فقط إن كان حسابك مسجلاً ومفعلاً.',
    CREATING: 'جاري الإنشاء...',
    REGISTER_SUCCESS: 'تم إنشاء الحساب بنجاح! جاري تسجيل الدخول...',
    LOGIN_ERROR: 'خطأ في تسجيل الدخول. تأكد من البريد وكلمة المرور.',
    REGISTER_ERROR: 'خطأ في الإنشاء',

    // Navigation
    NAV_DASHBOARD: 'لوحة التحكم',
    NAV_WORK_ORDERS: 'أوامر التشغيل',
    NAV_ACCOUNTANT: 'الخزينة والحسابات',
    NAV_SERVICES: 'الخدمات والتسعير',
    NAV_USERS: 'إدارة الموظفين',
    NAV_CUSTOMERS: 'العملاء والسيارات',
    NAV_PROFILE: 'إعدادات الحساب',

    // Page Titles
    TITLE_DASHBOARD: 'لوحة التحكم',
    TITLE_WORK_ORDERS: 'أوامر التشغيل',
    TITLE_ACCOUNTANT: 'الخزينة والحسابات',
    TITLE_SERVICES: 'الخدمات والتسعير',
    TITLE_USERS: 'إدارة الموظفين',
    TITLE_PROFILE: 'إعدادات الحساب',
    TITLE_NEW_ORDER: 'إصدار أمر تشغيل جديد',
    TITLE_ORDER_DETAILS: 'تفاصيل الأمر',

    // Dashboard
    TOTAL_CARS: 'إجمالي السيارات',
    CARS_IN_PROGRESS: 'سيارات قيد العمل',
    REVENUE_COLLECTED: 'الإيرادات المحصلة',
    OPEN_DEBT: 'الذمم المفتوحة',
    FINANCIAL_SUMMARY: 'الإيرادات (المحصل)',
    TOTAL_AMOUNT: 'المطلوب الإجمالي',
    WELCOME_TITLE: 'مرحباً بك في أمان كار',
    WELCOME_DESC: 'النظام متصل حالياً بقاعدة البيانات الحية.',
    RECENT_ACTIVITY: 'أحدث النشاطات',
    QUICK_ACTIONS: 'إجراءات سريعة',
    READY_TO_DELIVER: 'جاهزة للتسليم',
    LATE_ORDERS: 'متأخرة أو اقترب موعدها',
    NEW_ORDER_BTN: 'إصدار أمر جديد',
    NO_READY_CARS: 'لا توجد سيارات جاهزة للتسليم حالياً',
    NO_LATE_CARS: 'لا توجد سيارات متأخرة',
    PROFIT_CHART: 'مؤشر الأرباح والمبيعات',
    ALL_STAFF: 'كل الفنيين والموظفين',
    TODAY: 'اليوم',
    THIS_WEEK: 'هذا الأسبوع',
    THIS_MONTH: 'هذا الشهر',
    ALL_TIME: 'كل الأوقات',
    SAR: 'ر.س',
    OVERDUE: 'متأخر',
    APPROACHING: 'يقترب',

    // Work Orders
    ORDER_NUM: 'رقم الأمر',
    CREATED_DATE: 'تاريخ الإنشاء',
    DELIVERY_DATE: 'موعد التسليم',
    CUSTOMER: 'العميل',
    TECHNICIAN: 'الفني',
    TOTAL: 'الإجمالي',
    REMAINING: 'المتبقي',
    STATUS: 'الحالة',
    ALL: 'الكل',
    SEARCH_ORDERS: 'بحث باللوحة أو اسم العميل...',
    HIDE_CLOSED: 'إخفاء المغلق',
    ALL_TECHNICIANS: 'كل الفنيين',
    CUSTOMER_INFO: 'اسم العميل أو رقم الجوال',
    CUSTOMER_PLACEHOLDER: 'مثال: أحمد 0500000000',
    CAR_MODEL: 'ماركة وموديل السيارة',
    CAR_MODEL_PH: 'مثال: كامري 2022',
    CAR_PLATE: 'رقم اللوحة',
    CAR_PLATE_PH: 'ABC 123',
    SERVICES_SECTION: 'الخدمات المطلوبة',
    SEARCH_SERVICES: 'بحث بالخدمة...',
    LABOR_COST: 'أجور اليد (المصنعية) - ر.س',
    DISCOUNT: 'الخصم الممنوح - ر.س',
    CLIENT_NOTES: 'ملاحظات للعميل (قطع الغيار المُحضرة...)',
    INVOICE_TOTAL: 'إجمالي الفاتورة المتوقع',
    SERVICES_TOTAL: 'مجموع الخدمات والقطع',
    LABOR_ADDED: 'المصنعية المضافة',
    DISCOUNT_DEDUCTED: 'الخصم المخصوم',
    INTERNAL_NOTES: 'ملاحظات داخلية للفريق (تفاصيل فنية...)',
    ATTACH_FILE: 'إرفاق ملف/صورة',
    SAVE_DRAFT: 'حفظ كمسودة',
    SEND_TO_CASHIER: 'إرسال للخزينة',
    CANCEL_BACK: 'إلغاء والعودة',
    DELIVERY_MODAL_TITLE: 'تحديد موعد التسليم',
    DELIVERY_MODAL_DESC: 'حدد الموعد المتوقع للانتهاء وتسليمه للعميل.',
    START_WORK: 'بدء العمل',
    CANCEL: 'إلغاء',
    EDIT_ORDER: 'تعديل الأمر',
    NO_ORDERS: 'لا توجد أوامر تشغيل',

    // Order Statuses
    STATUS_DRAFT: 'مسودة',
    STATUS_PENDING_PAYMENT: 'بانتظار الدفع',
    STATUS_PARTIALLY_PAID: 'مدفوع جزئياً',
    STATUS_PAID_READY: 'مدفوع - جاهز للعمل',
    STATUS_IN_PROGRESS: 'قيد الصيانة',
    STATUS_READY: 'جاهز للتسليم',
    STATUS_CLOSED: 'تم الاستلام',

    // Order Filters
    FILTER_DRAFT: 'مسوده',
    FILTER_PENDING: 'مرسل للخزينه',
    FILTER_READY_WORK: 'جاهز للعمل',
    FILTER_IN_PROGRESS: 'قيد الصيانه',
    FILTER_READY_DELIVERY: 'جاهز للتسليم',
    FILTER_CLOSED: 'تم الاستلام',

    // Order Details
    CAR_CUSTOMER_INFO: 'بيانات العميل والسيارة',
    INVOICE_SERVICES: 'تفاصيل الفاتورة والخدمات',
    CURRENT_TECH: 'الفني الحالي',
    NET_AMOUNT: 'الصافي المطلوب',
    ACTIONS: 'الإجراءات',
    INTERNAL_NOTES_TITLE: 'الملاحظات الداخلية',
    AUDIT_LOG: 'سجل العمليات',
    ADD_NOTE: 'إرسال وحفظ',
    NOTE_PLACEHOLDER: 'اكتب ملاحظتك هنا...',
    NO_NOTES: 'لم تتم إضافة أي ملاحظات بعد.',
    NO_HISTORY: 'لا يوجد سجل.',
    REASSIGN_TECH: 'تحويل الفني',
    CONFIRM_ACTION: 'هل أنت متأكد؟',
    UNKNOWN: 'غير معروف',

    // Action Buttons (Order status transitions)
    BTN_APPROVE_PAYMENT: 'اعتماد الاستلام وإحالة للورشة',
    BTN_START_WORK: 'بدء أعمال الصيانة',
    BTN_MARK_READY: 'تحديد: جاهز للتسليم',
    BTN_CLOSE_ORDER: 'تسليم السيارة (إغلاق الأمر)',
    BTN_PARTIAL_PAYMENT: 'تسجيل دفعة جزئية',
    BTN_FULL_PAYMENT: 'تسجيل دفع كامل',
    PAYMENT_AMOUNT: 'المبلغ المدفوع (ر.س)',
    PAYMENT_REMAINING: 'المتبقي قبل الدفع',
    CONFIRM_PAYMENT: 'تأكيد الدفعة وحفظها',
    ACCESS_DENIED: 'ليس لديك صلاحية للقيام بهذا الإجراء.',

    // Accountant
    SEARCH_ACCOUNTANT: 'بحث رقم، لوحة، عميل...',
    REQUIRED_PAYMENT: 'المطلوب سداده',
    PAID_AMOUNT: 'المدفوع',
    FILTER_UNPAID: 'غير مسدد',
    FILTER_PARTIAL: 'مسدد جزئياً',
    FILTER_PAID: 'مسدد بالكامل',
    REFRESH: 'تحديث',

    // Services
    SERVICES_DESC: 'تعديل قائمة الخدمات المتاحة وأسعارها.',
    ADD_NEW_SERVICE: 'إضافة خدمة جديدة',
    SERVICE_NAME: 'اسم الخدمة',
    SERVICE_NAME_PH: 'مثال: تلميع سيارة',
    PRICE_SAR: 'السعر (ر.س)',
    SERVICE_ICON: 'أيقونة (FontAwesome)',
    SAVE_SERVICE: 'حفظ الخدمة',
    SERVICE_SAVED: 'تم حفظ الخدمة بنجاح',
    CONFIRM_ARCHIVE: 'هل تريد إخفاء هذه الخدمة؟',
    SEARCH_SERVICE: 'بحث باسم الخدمة...',
    ADD_DATE: 'تاريخ الإضافة',
    ACTION: 'إجراء',
    SERVICE_ICON_LABEL: 'الخدمة والأيقونة',
    NO_SERVICES: 'لا توجد خدمات. أضف خدمة جديدة.',

    // Users
    ADD_EMPLOYEE: 'إضافة موظف جديد',
    EMPLOYEE_NAME: 'اسم الموظف',
    EMPLOYEE_EMAIL: 'البريد الإلكتروني',
    TEMP_PASSWORD: 'كلمة المرور المؤقتة',
    ROLE_PERMISSION: 'الصلاحية والدور',
    ROLE_TECHNICIAN: 'فني صيانة',
    ROLE_ACCOUNTANT: 'محاسب',
    ROLE_ADMIN: 'مدير نظام',
    ROLE_RECEPTIONIST: 'موظف استقبال',
    ROLE_PENDING: 'حساب معلق (انتظار)',
    ROLE_SUSPENDED: 'موقوف',
    EMPLOYEES_LIST: 'قائمة الموظفين',
    NAME: 'الاسم',
    ROLE: 'الدور',
    JOIN_DATE: 'تاريخ الانضمام',
    SEARCH_USERS: 'بحث بموظفي الورشة...',
    CREATE_ACCOUNT: 'إنشاء حساب الموظف',
    USER_CREATED: 'تم إنشاء حساب الموظف بنجاح',
    RATE_LIMIT_ERROR: 'تجاوزت الحد المسموح. يرجى الانتظار قليلاً.',

    // Profile
    EDIT_PROFILE: 'تعديل بيانات الحساب',
    NEW_PASSWORD: 'كلمة المرور الجديدة',
    NEW_PASSWORD_PH: 'اتركه فارغاً لعدم التغيير',
    CHANGE_AVATAR: 'تغيير الصورة الشخصية',
    SAVE_CHANGES: 'حفظ التعديلات',
    PROFILE_SAVED: 'تم حفظ إعدادات الحساب بنجاح',
    PASSWORD_CHANGE_NOTE: 'سيُطلب منك تسجيل الدخول مجدداً عند تغيير كلمة المرور.',

    // Pending/Suspended
    PENDING_TITLE: 'حسابك قيد المراجعة',
    PENDING_DESC: 'حسابك مسجل بنجاح ولكن لم تُعيَّن له صلاحيات بعد. يرجى التواصل مع مدير النظام.',
    SUSPENDED_TITLE: 'تم إيقاف حسابك',
    SUSPENDED_DESC: 'لقد تم تعطيل صلاحيات هذا الحساب من قِبل إدارة النظام.',

    // General
    SUCCESS: 'تمت العملية بنجاح',
    ERROR: 'حدث خطأ',
    CONFIRM_CLOSE: 'هل أنت متأكد؟',
    CONFIRM_CLOSE_ORDER: 'هل تريد إغلاق هذا الأمر وتسليم السيارة؟',
    NO_URGENT_ALERTS: 'لا توجد تنبيهات حالياً',
    VIEW_ROLE_AS: 'وضع المشاهدة كـ',
    NOTIFICATIONS: 'تنبيهات مواعيد التسليم',
    NO_NOTIFICATIONS: 'لا توجد تنبيهات حالياً.',
    HELLO: 'مرحباً',
    LANGUAGE: 'English / عربي',
    MONTHS: ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'],
  },

  en: {
    APP_NAME: 'Aman Car',
    APP_TAGLINE: 'Workshop Management System',
    STAFF_PORTAL: 'Staff Portal',
    LOADING: 'Loading...',
    SAVING: 'Saving...',
    UPDATING: 'Updating...',
    PROCESSING: 'Processing...',
    SYSTEM_LOADING: 'Loading system...',
    UPDATING_DATA: 'Updating data...',
    EMAIL_LBL: 'Email Address',
    PASSWORD_LBL: 'Password',
    LOGIN_btn: 'Sign In',
    REGISTER_btn: 'Create Account',
    LOGOUT: 'Sign Out',
    NO_ACCOUNT: "Don't have an account? Sign up",
    HAS_ACCOUNT: 'Already have an account? Sign in',
    FULL_NAME: 'Full Name',
    LOGIN_NOTE: 'Note: System connects to a live database. Only registered active accounts can log in.',
    CREATING: 'Creating...',
    REGISTER_SUCCESS: 'Account created successfully! Logging in...',
    LOGIN_ERROR: 'Login failed. Check your email and password.',
    REGISTER_ERROR: 'Registration error',
    NAV_DASHBOARD: 'Dashboard',
    NAV_WORK_ORDERS: 'Work Orders',
    NAV_ACCOUNTANT: 'Cashier & Accounts',
    NAV_SERVICES: 'Services & Pricing',
    NAV_CUSTOMERS: 'Customers & Cars',
    NAV_USERS: 'Staff Management',
    NAV_PROFILE: 'Account Settings',
    TITLE_DASHBOARD: 'Dashboard',
    TITLE_WORK_ORDERS: 'Work Orders',
    TITLE_ACCOUNTANT: 'Cashier & Accounts',
    TITLE_SERVICES: 'Services & Pricing',
    TITLE_USERS: 'Staff Management',
    TITLE_PROFILE: 'Account Settings',
    TITLE_NEW_ORDER: 'New Work Order',
    TITLE_ORDER_DETAILS: 'Order Details',
    TOTAL_CARS: 'Total Cars',
    CARS_IN_PROGRESS: 'Cars in Progress',
    REVENUE_COLLECTED: 'Revenue Collected',
    OPEN_DEBT: 'Open Receivables',
    FINANCIAL_SUMMARY: 'Revenue (Collected)',
    TOTAL_AMOUNT: 'Total Required',
    WELCOME_TITLE: 'Welcome to Aman Car',
    WELCOME_DESC: 'System is connected to live database.',
    RECENT_ACTIVITY: 'Recent Activity',
    QUICK_ACTIONS: 'Quick Actions',
    READY_TO_DELIVER: 'Ready to Deliver',
    LATE_ORDERS: 'Late or Approaching',
    NEW_ORDER_BTN: 'New Work Order',
    NO_READY_CARS: 'No cars ready for delivery',
    NO_LATE_CARS: 'No late deliveries',
    PROFIT_CHART: 'Revenue & Sales Chart',
    ALL_STAFF: 'All Staff & Technicians',
    TODAY: 'Today',
    THIS_WEEK: 'This Week',
    THIS_MONTH: 'This Month',
    ALL_TIME: 'All Time',
    SAR: 'SAR',
    OVERDUE: 'Overdue',
    APPROACHING: 'Approaching',
    ORDER_NUM: 'Order #',
    CREATED_DATE: 'Created',
    DELIVERY_DATE: 'Delivery',
    CUSTOMER: 'Customer',
    TECHNICIAN: 'Technician',
    TOTAL: 'Total',
    REMAINING: 'Remaining',
    STATUS: 'Status',
    ALL: 'All',
    SEARCH_ORDERS: 'Search by plate or customer...',
    HIDE_CLOSED: 'Hide Closed',
    ALL_TECHNICIANS: 'All Technicians',
    CUSTOMER_INFO: 'Customer name or phone',
    CUSTOMER_PLACEHOLDER: 'Ex: Ahmed 0500000000',
    CAR_MODEL: 'Car Make & Model',
    CAR_MODEL_PH: 'Ex: Camry 2022',
    CAR_PLATE: 'License Plate',
    CAR_PLATE_PH: 'ABC 123',
    SERVICES_SECTION: 'Services Required',
    SEARCH_SERVICES: 'Search service...',
    LABOR_COST: 'Labor Cost (SAR)',
    DISCOUNT: 'Discount (SAR)',
    CLIENT_NOTES: 'Notes for customer (spare parts provided...)',
    INVOICE_TOTAL: 'Invoice Total',
    SERVICES_TOTAL: 'Services & Parts Total',
    LABOR_ADDED: 'Labor Added',
    DISCOUNT_DEDUCTED: 'Discount',
    INTERNAL_NOTES: 'Internal team notes...',
    ATTACH_FILE: 'Attach File/Photo',
    SAVE_DRAFT: 'Save Draft',
    SEND_TO_CASHIER: 'Send to Cashier',
    CANCEL_BACK: 'Cancel & Back',
    DELIVERY_MODAL_TITLE: 'Set Delivery Date',
    DELIVERY_MODAL_DESC: 'Set the expected delivery date for the customer.',
    START_WORK: 'Start Work',
    CANCEL: 'Cancel',
    EDIT_ORDER: 'Edit Order',
    NO_ORDERS: 'No work orders found',
    STATUS_DRAFT: 'Draft',
    STATUS_PENDING_PAYMENT: 'Pending Payment',
    STATUS_PARTIALLY_PAID: 'Partially Paid',
    STATUS_PAID_READY: 'Paid - Ready for Work',
    STATUS_IN_PROGRESS: 'In Progress',
    STATUS_READY: 'Ready for Delivery',
    STATUS_CLOSED: 'Closed',
    FILTER_DRAFT: 'Draft',
    FILTER_PENDING: 'Pending',
    FILTER_READY_WORK: 'Ready for Work',
    FILTER_IN_PROGRESS: 'In Progress',
    FILTER_READY_DELIVERY: 'Ready for Delivery',
    FILTER_CLOSED: 'Closed',
    CAR_CUSTOMER_INFO: 'Customer & Car Info',
    INVOICE_SERVICES: 'Invoice & Services',
    CURRENT_TECH: 'Assigned Technician',
    NET_AMOUNT: 'Net Amount Due',
    ACTIONS: 'Actions',
    INTERNAL_NOTES_TITLE: 'Internal Notes',
    AUDIT_LOG: 'Audit Log',
    ADD_NOTE: 'Send & Save',
    NOTE_PLACEHOLDER: 'Write your note here...',
    NO_NOTES: 'No internal notes yet.',
    NO_HISTORY: 'No history.',
    REASSIGN_TECH: 'Reassign Technician',
    CONFIRM_ACTION: 'Are you sure?',
    UNKNOWN: 'Unknown',
    BTN_APPROVE_PAYMENT: 'Approve Payment & Send to Workshop',
    BTN_START_WORK: 'Start Maintenance',
    BTN_MARK_READY: 'Mark as Ready for Delivery',
    BTN_CLOSE_ORDER: 'Close Order (Delivered)',
    BTN_PARTIAL_PAYMENT: 'Record Partial Payment',
    BTN_FULL_PAYMENT: 'Record Full Payment',
    PAYMENT_AMOUNT: 'Amount Paid (SAR)',
    PAYMENT_REMAINING: 'Remaining Before Payment',
    CONFIRM_PAYMENT: 'Confirm Payment',
    ACCESS_DENIED: 'You do not have permission for this action.',
    SEARCH_ACCOUNTANT: 'Search order, plate, customer...',
    REQUIRED_PAYMENT: 'Amount Due',
    PAID_AMOUNT: 'Paid',
    FILTER_UNPAID: 'Unpaid',
    FILTER_PARTIAL: 'Partially Paid',
    FILTER_PAID: 'Fully Paid',
    REFRESH: 'Refresh',
    SERVICES_DESC: 'Manage available services and pricing.',
    ADD_NEW_SERVICE: 'Add New Service',
    SERVICE_NAME: 'Service Name',
    SERVICE_NAME_PH: 'Ex: Car Polish',
    PRICE_SAR: 'Price (SAR)',
    SERVICE_ICON: 'Icon (FontAwesome)',
    SAVE_SERVICE: 'Save Service',
    SERVICE_SAVED: 'Service saved successfully',
    CONFIRM_ARCHIVE: 'Hide this service?',
    SEARCH_SERVICE: 'Search service name...',
    ADD_DATE: 'Date Added',
    ACTION: 'Action',
    SERVICE_ICON_LABEL: 'Service & Icon',
    NO_SERVICES: 'No services found. Add one!',
    ADD_EMPLOYEE: 'Add New Employee',
    EMPLOYEE_NAME: 'Employee Name',
    EMPLOYEE_EMAIL: 'Email Address',
    TEMP_PASSWORD: 'Temporary Password',
    ROLE_PERMISSION: 'Role & Permission',
    ROLE_TECHNICIAN: 'Technician',
    ROLE_ACCOUNTANT: 'Accountant',
    ROLE_ADMIN: 'System Admin',
    ROLE_RECEPTIONIST: 'Receptionist',
    ROLE_PENDING: 'Pending Account',
    ROLE_SUSPENDED: 'Suspended',
    EMPLOYEES_LIST: 'Employee List',
    NAME: 'Name',
    ROLE: 'Role',
    JOIN_DATE: 'Join Date',
    SEARCH_USERS: 'Search employees...',
    CREATE_ACCOUNT: 'Create Employee Account',
    USER_CREATED: 'Employee account created successfully',
    RATE_LIMIT_ERROR: 'Rate limit exceeded. Please wait a moment.',
    EDIT_PROFILE: 'Edit Account Info',
    NEW_PASSWORD: 'New Password',
    NEW_PASSWORD_PH: 'Leave blank to keep current password',
    CHANGE_AVATAR: 'Change Profile Photo',
    SAVE_CHANGES: 'Save Changes',
    PROFILE_SAVED: 'Profile settings saved successfully',
    PASSWORD_CHANGE_NOTE: 'You will be logged out upon password change.',
    PENDING_TITLE: 'Account Under Review',
    PENDING_DESC: 'Your account is registered but no permissions have been assigned yet. Please contact the system administrator.',
    SUSPENDED_TITLE: 'Account Suspended',
    SUSPENDED_DESC: 'This account has been suspended by system administration.',
    SUCCESS: 'Operation completed successfully',
    ERROR: 'An error occurred',
    CONFIRM_CLOSE: 'Are you sure?',
    CONFIRM_CLOSE_ORDER: 'Close this order and confirm delivery?',
    NO_URGENT_ALERTS: 'No alerts at this time',
    VIEW_ROLE_AS: 'View as',
    NOTIFICATIONS: 'Delivery Notifications',
    NO_NOTIFICATIONS: 'No notifications.',
    HELLO: 'Hello',
    LANGUAGE: 'English / عربي',
    MONTHS: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
  }
};

let currentLang = localStorage.getItem('lang') || 'ar';

window.t = function(key) {
  return (translations[currentLang] && translations[currentLang][key]) || translations['ar'][key] || key;
};

window.getLang = function() { return currentLang; };

window.toggleLanguage = function() {
  currentLang = currentLang === 'ar' ? 'en' : 'ar';
  localStorage.setItem('lang', currentLang);
  document.documentElement.lang = currentLang;
  document.documentElement.dir = currentLang === 'ar' ? 'rtl' : 'ltr';
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    el.textContent = window.t(key);
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    el.placeholder = window.t(el.getAttribute('data-i18n-ph'));
  });
};

// Apply language on load
document.documentElement.lang = currentLang;
document.documentElement.dir = currentLang === 'ar' ? 'rtl' : 'ltr';
